name = "showdown-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "e1c7770c3e49a3a72eb4d6be53588fb0"

routes = [
  # showdown.run will be added once Cloudflare zone is active (NS propagation from Spaceship)
  { pattern = "showdown.rdyson.dev", custom_domain = true }
]
